spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: photonChat
      username: root
      password: 1234
      uri: mongodb://root:1234@localhost:27017/admin